disabled = false
locale = "en"
label = "English"
weight = 1
title = "Iron Carrot Archives"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/specialized_3.png"
  logo = "img/tb.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Home of TacticaBreakfast's Arknights guides and works."
  copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "TacticalBreakfast"
   email = "TacBreakfast@gmail.com"
   image = "img/tb.png"
   imageQuality = 96
   headline = "I'm only Cautus."
   bio = "Writer and Bunny Lover."
   links = [
     { email = "mailto:TacBreakfast@gmail.com" },
     { bluesky = "https://bsky.app/profile/tacticalbreakfast.bsky.social" },
     { discord = "https://discord.com/users/tacticalbreakfast" },
     { reddit = "https://reddit.com/user/tacticalbreakfast" },
#     { twitter = "https://twitter.com/tacbreakfast1" },
     { x-twitter = "https://twitter.com/tacbreakfast1" },
     { youtube = "https://www.youtube.com/@tacticalbreakfast2271" }
#     { ko-fi = "https://ko-fi.com/username" },
   ]
