# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Masteries"
  pageRef = "masteries"
  weight = 10

[[main]]
  name = "Most Recent"
  parent = "Masteries"
  pageRef = "masteries/mostrecent"
  weight = 9

[[main]]
  name = "Vanguards"
  parent = "Masteries"
  pageRef = "masteries/vanguards"
  weight = 10

[[main]]
  name = "Guards"
  parent = "Masteries"
  pageRef = "masteries/guards"
  weight = 11

[[main]]
  name = "Defenders"
  parent = "Masteries"
  pageRef = "masteries/defenders"
  weight = 12

[[main]]
  name = "Snipers"
  parent = "Masteries"
  pageRef = "masteries/snipers"
  weight = 13

[[main]]
  name = "Casters"
  parent = "Masteries"
  pageRef = "masteries/casters"
  weight = 14

[[main]]
  name = "Medics"
  parent = "Masteries"
  pageRef = "masteries/medics"
  weight = 15

[[main]]
  name = "Supporters"
  parent = "Masteries"
  pageRef = "masteries/supporters"
  weight = 16

[[main]]
  name = "Specialists"
  parent = "Masteries"
  pageRef = "masteries/specialists"
  weight = 17

[[main]]
  name = "CN Lookahead"
  parent = "Masteries"
  pageRef = "masteries/lookahead"
  weight = 18

[[main]]
  name = "Glossary"
  parent = "Masteries"
  pageRef = "masteries/glossary"
  weight = 19

[[main]]
  name = "Efficiency Sheets"
  pageRef = "posts"
  weight = 15

[[main]]
  name = "Paid Packs"
  parent = "Efficiency Sheets"
  url = "https://docs.google.com/spreadsheets/d/1knwIQHQXDfmAIEShW3QuybzBh9OerfHsYJgCVVYXqtw/"
  weight = 15

[[main]]
  name = "M3/E2 Tickets"
  parent = "Efficiency Sheets"
  url = "https://docs.google.com/spreadsheets/d/1knwIQHQXDfmAIEShW3QuybzBh9OerfHsYJgCVVYXqtw/"
  weight = 20

[[main]]
  name = "Other Content"
  weight = 20

[[main]]
  name = "Tier List"
  parent = "Other Content"
  url = "https://docs.google.com/spreadsheets/d/1E7HmgKWiV8pKpJpvpVzziYxnaQTP01Vtw_PXEdL7XPA/"
  weight = 20

[[main]]
  name = "Blog"
  parent = "Other Content"
  pageRef = "posts"
  weight = 25

[[main]]
  name = "Fiction"
  parent = "Other Content"
  url = "https://archiveofourown.org/users/TacticalBreakfast"
  weight = 30

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Topics"
#   pageRef = "topics"
#   weight = 10
